feat: support aggregating metrics across workers in a Node.js worker_…
siimon/prom-client pull request #403
Opened 2020-10-15 13:26 UTC by rafixer

…threads

2021-01-23 17:59 UTC, zbjornson requested changes
Thanks for opening this and sorry it took forever to get reviewed. A few comments below, plus:

- [ ] Looks like Node.js 10 breaks
- [ ] Needs a changelog update
- [ ] Please add tests

2021-01-23 17:59 UTC, zbjornson commented on lib/cluster.js
> +const workersQueue = [];
Should this be scoped to the AggregatorRegistry instance?

2021-01-23 17:59 UTC, zbjornson commented on lib/cluster.js
> +					if (cluster().isWorker) {
I have no experience with worker threads. Can they be used (and are they ever practically used) in conjunction with the cluster module?

2021-05-05 13:54 UTC, bgalek commented
@zbjornson node 10 met its EOL https://nodejs.org/en/about/releases/ maybe we should not test against it anymore? worker features are available from node 11.00

2021-05-12 06:24 UTC, SimenB commented
Dropping node 10 must be done in a major release, but we can probably do one of those?

2021-07-23 13:42 UTC, alec-benson commented
any chance we could push this along? I am using worker threads on a project and this would help a lot.

2021-07-23 13:43 UTC, bgalek commented
@rafixer @zbjornson? :)

2022-01-01 20:19 UTC, zbjornson commented
This looks good.

We have two other PRs staged for a semver-major release. Let's drop v10 support in that release and land this PR with it.

(I can add the changelog and fix the merge conflict if @rafixer doesn't get to it.)

2022-02-18 17:24 UTC, bgalek commented
@zbjornson any chanses soon?:)

2022-02-28 08:05 UTC, bgalek commented
@zbjornson? :)

2022-06-02 16:05 UTC, Zagorodnyi commented
Any news about this feature?

2022-06-02 17:19 UTC, rafixer commented
Sorry for no action about this PR. I will back to this on next week!

2023-01-17 13:48 UTC, SimenB requested changes
sorry about the slow response! can you update the documentation?

2023-01-17 13:48 UTC, SimenB commented on lib/workerThreads.js
> +
```suggestion
```

2023-01-17 13:48 UTC, SimenB commented on lib/workerThreads.js
> +}
```suggestion
const worker_threads = require('worker_threads');
```

2023-01-17 14:02 UTC, rafixer commented
> sorry about the slow response! can you update the documentation?

also, I will check why currently tests cases are failing

2023-01-17 14:04 UTC, SimenB commented
there's a syntax error. Miiight be the merge? [`ee05476` (#403)](https://github.com/siimon/prom-client/pull/403/commits/ee0547646a000eeb87c3839689983f7e890856ad). I didn't get any merge conflicts, tho

2023-01-17 14:12 UTC, SimenB commented
Fixing the syntax error gives a bunch of lint errors, so I dunno 😅

2023-01-17 14:59 UTC, SimenB commented
thread communication shouldn't be any slower than separate process, should it?

2023-03-13 08:09 UTC, SimenB commented
@rafixer could you target `master` with this (and resolve conflicts)?

2023-03-13 14:46 UTC, rafixer commented
> @rafixer could you target `master` with this (and resolve conflicts)?

Target changed , resolving conflicts in progress!

2023-03-15 16:28 UTC, bgalek approved these changes

2023-06-26 11:52 UTC, infloop commented
@SimenB  @zbjornson Are there any updates yet? Does this need any help?

2024-07-08 19:47 UTC, matthieu-beteille commented
@SimenB @zbjornson Any update on this? Anything we can do to push this through?

2024-07-25 16:58 UTC, nrathi commented
+1, this would really help me as well!

2024-07-25 17:08 UTC, SimenB requested changes
is it possible to write tests for this? Probably by spinning up some process which emulates this and making requests against it?

I can't speak to the feature itself as I've never used the cluster mode

2024-07-25 17:08 UTC, SimenB commented on lib/cluster.js
> +				request.pending += message.workerRequests || 0;
```suggestion
				if (message.workerRequests) {
					request.pending += message.workerRequests;
				}
```

2024-07-25 17:08 UTC, SimenB commented on lib/cluster.js
> +					if (worker && worker instanceof Worker) {
```suggestion
					if (worker instanceof Worker) {
```

2024-07-25 17:08 UTC, SimenB commented on lib/cluster.js
> +					if (worker && worker instanceof Worker) {
should we check this when instantiating/pushing into `workersQueue` rather than when receiving messages? We should probably throw

2024-07-25 17:08 UTC, SimenB commented on lib/cluster.js
> +				workersQueue.forEach(worker => {
use `for-of` instead of `forEach`

2024-07-25 17:08 UTC, SimenB commented on lib/cluster.js
> +					.then(metrics => {
can we use async-await rather than `.then` and `.catch`?

2026-07-03 01:03 UTC, jdmarshall commented
Covered by #693

2026-07-03 01:03 UTC, closed without merging