Use Nullish Coalescing Operator in inc()
siimon/prom-client pull request #446
Opened 2021-07-06 10:46 UTC by dapplion

Calling `.inc(value)` with a dynamic value that may be 0 or 1 will always cause to increase metrics by 1. This is very problematic and may distort the metrics in a non obvious way

2021-07-06 15:51 UTC, zbjornson commented
Good find. We can't use the `??` operator though because we currently support older versions of Node. Can you use an alternative fix please?

2021-07-06 16:47 UTC, dapplion commented
> Good find. We can't use the `??` operator though because we currently support older versions of Node. Can you use an alternative fix please?

Sure, let me know if this approach is more suitable

https://github.com/siimon/prom-client/blob/21406a0a43455ce8e6a4b705afd9333ce7398114/lib/gauge.js#L149

2021-07-07 15:03 UTC, zbjornson commented
That works! Can you also add a test and update the changelog please?

2021-07-31 17:23 UTC, zbjornson requested changes
Sorry about the delay.

Two little changes to make, then should be set! Thanks.

2021-07-31 17:23 UTC, zbjornson commented on lib/gauge.js
> +		const value = data.value === undefined ? 1 : data.value
Need a different variable name since `value` is also a parameter name.
Also need a semicolon at the end.

(ditto for changes below)

2021-08-01 17:19 UTC, zbjornson approved these changes
Thanks!

I changed the impl a little bit so the linter passes, and added another test.

2021-08-01 17:19 UTC, merged