fix: enable bun.js by catching NotImplemented error
siimon/prom-client pull request #624
Opened 2024-04-02 19:46 UTC by owlcode

Catch [error thrown by bun.js](https://github.com/oven-sh/bun/blob/801e475c72b3573a91e0fb4c3afdd53b437770e1/src/js/node/perf_hooks.ts#L158) when calling `perf_hooks.monitorEventLoopDelay`

Following up on https://github.com/siimon/prom-client/pull/599 - bun.js already introduced some of the missing APIs (or created stubs) so to the best of my knowledge this is the last thing which is required to make default gc stats work for bun (at least it worked for me with this change).
Error is also reported in bun's repository - https://github.com/oven-sh/bun/issues/4708#issuecomment-2030436691

Fixes https://github.com/siimon/prom-client/issues/570

2024-04-03 07:54 UTC, SimenB requested changes

2024-04-03 07:54 UTC, SimenB commented on lib/metrics/eventLoopLag.js
> +		}
the `catch` should check for the specific error bun throws and rethrow any other

2024-04-03 07:54 UTC, SimenB commented on lib/metrics/heapSpacesSizeAndUsed.js
> +	}
ditto

2024-04-03 09:19 UTC, SimenB commented
Can you include the CI stuff from #599?

2024-04-03 09:53 UTC, owlcode commented
> Can you include the CI stuff from https://github.com/siimon/prom-client/pull/599?

Done

2024-04-08 17:52 UTC, merged

2024-04-16 06:15 UTC, SimenB commented
https://github.com/siimon/prom-client/releases/tag/v15.1.2